name: App pipeline  

on:
push:
    branches:
    - main
pull_request:
    branches:
    - main

jobs:
build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build
        run: mvn clean install --no-transfer-progress -Dmaven.test.skip=true

    - name: Tests
        run: mvn test --no-transfer-progress
